# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Skippo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Skippo
  pod 'PageMenu' ,:git => "https://github.com/mouse-lin/PageMenu.git"

  target 'SkippoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SkippoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
